<?php

/**
 * @file
 * Provide Theme declaration for Newsletter Signup Field Type.
 */

/**
 * Implements hook_theme().
 */
function infomaniak_newsletter_field_theme($existing, $type, $theme, $path) {
  return [
    'newsletter_signup_message' => [
      'variables' => [
        'status' => NULL,
        'message' => NULL,
        'errors' => [],
      ],
    ],
    'newsletter_signup_validation' => [
      'variables' => [
        'message' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function infomaniak_newsletter_field_mail($key, &$message, $params) {
  switch ($key) {
    case 'subscription_validation':
      $message['subject'] = $params['subject'];
      $message['body'] = $params['body'];
      break;
  }
}
